masking_patterns:
  - type: "Passwords"
    prefix: "PASSWORD"
    regex:
      - >
        (пароль:
        |password:
        |ПАРОЛЬ:
        |PASSWORD:
        |Пароль:
        |Password:
        |пароль
        |password
        |ПАРОЛЬ
        |PASSWORD
        |Пароль
        |Password
        |PWD:)\s*(\S+)