masking_patterns:
  - type: "Code Words"
    prefix: "CODE_WORD"
    regex:
      - >
        (?i)(кодовое слово|кодслово|кодовое|секретное слово|секретный код|код доступа|пароль|ключевое слово|идентификатор|код подтверждения|код безопасности|код авторизации|код пользователя|запоминающее слово|код-фраза|код-пароль|код-идентификатор|код-подтверждение|код-авторизации|код-защиты|код-доступа|код-подтверждения личности|код-ключ|код-секрет|код)\s*[:;\s\-/><(это)]*(\S+)