masking_patterns:
  - type: "Home Phones"
    prefix: "HOME_PHONE"
    regex:
      - (?i)(домашний телефон:|Домашний телефон:|домашний телефон|Домашний телефон|дом. тел:|дом.тел.:|дом. тел|дом.тел)\s*(\b\d{6,}\b)