masking_patterns:
  - type: "Token Hashes"
    prefix: "TOKEN_HASH"
    regex:
      - \b[a-fA-F0-9]{16}\b
      - \b[a-fA-F0-9]{32}\b
      - \b[a-fA-F0-9]{40}\b
      - \b[a-fA-F0-9]{64}\b
      - \b[a-fA-F0-9]{128}\b
      - \b[a-zA-Z0-9_-]{16}\b
