masking_patterns:
  - type: "CVC/CVV Codes"
    prefix: "CVC_CVV"
    regex:
      - >
        (?i)(cvv|cvc|cvp|CVV\s*код:|CVC\s*код:|CVV2\s*код:|CVC2\s*код:|CVC2|CVV:|CVC|CVV2|свв|свс|свп|три\s*цифры|на\s*обороте|код|безопасный\s*код|защитный\s*код|Код\s*безопасности|код\s*подтверждения|код\s*проверки|дополнительный\s*код|код\s*карты|код\s*на\s*обороте|код\s*доступа|контрольный\s*код|Security\s*code)[\s:\n_\.-]*\s?(\d{3})