masking_patterns:
  - type: "Dates"
    prefix: "DATE"
    regex:
      - '\b(0?[1-9]|[12][0-9]|3[01])\s(янв(?:аря)?|февр(?:аля)?|мар(?:та)?|апр(?:еля)?|мая|июн(?:я)?|июл(?:я)?|авг(?:уста)?|сент(?:ября)?|окт(?:ября)?|нояб(?:ря)?|дек(?:абря)?)(?:\s(19[0-9]{2}|20[0-9]{2}|(\d{2}))(?:г\.?|год(?:а)?)?)?\b'
      - '\b([0-2]?[0-9]|3[01])([ -./])(0?[1-9]|1[0-2])(?:\2((\d{2})|(\d{4}))(?:г\.?|год(?:а)?)?)?\b'
        