masking_patterns:
  - type: "File Paths"
    prefix: "FILE_PATH"
    regex:
      - "\\b[A-Z]:[\\\\/](?:[\\w\\s.-]+[\\\\/]?)*"
      - "\\\\[\\w\\s.-]+(?:\\\\[\\w\\s.-]+)*"
      - "/[\\w\\s.-]+(?:/[\\w\\s.-]+)*"
      - "//[\\w\\s.-]+(?:/[\\w\\s.-]+)*"
      - "\\\\[\\w\\s.-]+(?:\\\\[\\w\\s.-]+)*"
