masking_patterns:
  - type: "Money"
    prefix: "MONEY"
    regex:
      - >
        \b(?:сумма:?\s*)?\d{1,3}(?:[.,]\d{3})*(?:[.,]\d{0,2})?\s*(?:рубл[ей]|долларов|евро|£|\$|€)\b
      - >
        \b\d{1,3}(?:[.,]\d{3})*(?:[.,]\d{0,2})?\s*(?:рубл[ей]|долларов|евро|£|\$|€)\b
      - >
        \b(?:сумма:?\s*)?\d{1,3}(?:[.,]\d{3})*(?:[.,]\d{0,2})?\b
      - >
        \b(?:£|\$|€)?\d{1,3}(?:[.,]\d{3})*(?:[.,]\d{0,2})?\s*(?:рубл[ей]|долларов|евро)?\b

